server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;
    root /var/www/app;
    index index.html index.php;

    # Логи доступа
    access_log /var/log/nginx/app_access.log;
    error_log  /var/log/nginx/app_error.log;

    # Главная страница
    location / {
        try_files $uri $uri/ /index.html;
    }

    # PHP-обработка через php-fpm
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php8.1-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        
    }

    # Запрет доступа к скрытым файлам
    location ~ /\. {
        deny all;
    }
}
